### PR TITLE
Updated DoneCommand to correct mode and Save Name Issue

### LINKED ISSUE #160: [PE-D] Done command executes while in notebook mode.
A user might have thought that he can mark a notebook as done while in reality he affects major changes to data in timetable.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: thatseant/ped#8

### LINKED ISSUE #162: [PE-D] Name is not correct when running the program after exiting.
Running the jar file after exiting the program results in the change of name as shown above.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: 1-Karthigeyan-1/ped#1

### LINKED ISSUE #168: [PE-D] Did not save name properly
Initially prompted to enter my name when entering program for the first time.
Upon exiting and entering the program, name was different from what I entered initially. (changed form 'teng' to 'Tom')

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: tengkianen/ped#2

### LINKED ISSUE #179: [PE-D] Correct Mode Bug
When in the incorrect mode, and a input of command for the other mode suppose to throw an exception message of "Please check that you are in the correct mode" However done can be done within timetable mode and notebook mode, if this is a functionality then it could be mentioned in the UG and ignore this. 

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: tobiasceg/ped#2

### PR DESCRIPTION
**Pull request by yAOwzers**
Done Command can only be executed in Timetable mode. Else, an error message will be printed guiding the user to enter the timetable mode to use the done command.

Made command words non-case sensitive, idk if that is what we want, please review and let me know.

### CODE REVIEW

**Comment by yAOwzers** [comment]
Updated to be case-sensitive command words

**Review by franceneee — APPROVED** [review]
Looks good!

**Review by Lusi711 — CHANGES_REQUESTED** [review]
Some checkstyle errors

**Comment by yAOwzers** [comment]
Updated the path for the saving of the name, realised that the name data was saving and read off 2 separate files.

**Review by franceneee — APPROVED** [review]

**Review by Lusi711 — APPROVED** [review]

**Pull request merged**
