### PR TITLE
Fix bugs

### PR DESCRIPTION
**Pull request by franceneee**

### CODE REVIEW

**Review by NeilBaner — APPROVED** [review]
Great! 😃

**Comment by NeilBaner** [comment]
Thanks for the fixes @chuckiex3! Since you requested review from everyone else too, should I wait for more people to review before merging? I think it should be fine though.

**Comment by franceneee** [comment]
if you think it's good enough then merge it please 😛

**Comment by NeilBaner** [comment]
Your wish is my `seedu.Duke.userinterface.Command` :)

**Pull request merged**
